services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS=*
    # Для GPU:
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]


  postgres:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE

  milvus:
    image: milvusdb/milvus:v3.0-beta
    command: [ "milvus", "run", "standalone" ]
    environment:
      ETCD_USE_EMBED: "true"
      ETCD_DATA_DIR: /var/lib/milvus/etcd
      ETCD_CONFIG_PATH: /milvus/configs/embedEtcd.yaml
      COMMON_STORAGETYPE: local
      DEPLOY_MODE: STANDALONE
    volumes:
      - milvus_data:/var/lib/milvus
      - ./infra/milvus/embedEtcd.yaml:/milvus/configs/embedEtcd.yaml
      - ./infra/milvus/user.yaml:/milvus/configs/user.yaml
    ports:
      - "19530:19530"
      - "9091:9091"

  attu:
    image: zilliz/attu:v3.0.0-beta.6
    ports:
      - "3000:3000"
    environment:
      - MILVUS_ADDRESS=milvus:19530
    volumes:
      - milvus_attu_data:/data
    depends_on:
      - milvus

volumes:
  ollama_data:
  pg_data:
  qdrant_data:
  chroma_data:
  milvus_data:
  milvus_attu_data:
