POINTS = [
    {
        "id": 1,
        "text": "Нейросети на основе трансформеров показывают выдающиеся результаты в обработке естественного языка...",
        "metadata": {
            "title": "Обзор Transformer-архитектур",
            "author": "А. Петров",
            "category": "наука",
            "tags": ["AI", "NLP", "transformers"],
            "published_date": "2025-01-15T10:00:00Z",
            "rating": 4.8,
            "access_level": "public",
            "department": "research",
            "version": 2,
        },
    },
    {
        "id": 2,
        "text": "Применение квантовых вычислений в криптографии: текущее состояние и перспективы...",
        "metadata": {
            "title": "Квантовая криптография 2025",
            "author": "М. Иванова",
            "category": "техника",
            "tags": ["quantum", "cryptography", "security"],
            "published_date": "2025-02-20T14:30:00Z",
            "rating": 4.2,
            "access_level": "restricted",
            "department": "engineering",
            "version": 1,
        },
    },
    {
        "id": 3,
        "text": "Рынок ИИ-стартапов в 2024 году: инвестиции выросли на 30%...",
        "metadata": {
            "title": "Инвестиции в AI",
            "author": "С. Козлов",
            "category": "бизнес",
            "tags": ["AI", "startups", "finance"],
            "published_date": "2024-12-10T09:15:00Z",
            "rating": 3.9,
            "access_level": "public",
            "department": "marketing",
            "version": 1,
        },
    },
    {
        "id": 4,
        "text": "Новая методика ранней диагностики онкозаболеваний с использованием глубокого обучения...",
        "metadata": {
            "title": "Deep Learning в онкологии",
            "author": "Е. Смирнова",
            "category": "медицина",
            "tags": ["AI", "healthcare", "diagnostics"],
            "published_date": "2025-03-01T08:00:00Z",
            "rating": 4.9,
            "access_level": "confidential",
            "department": "research",
            "version": 3,
        },
    },
    {
        "id": 5,
        "text": "Блокчейн для управления цепочками поставок: практические кейсы...",
        "metadata": {
            "title": "Blockchain в логистике",
            "author": "Д. Волков",
            "category": "техника",
            "tags": ["blockchain", "supply chain", "logistics"],
            "published_date": "2024-11-05T11:20:00Z",
            "rating": 4.0,
            "access_level": "public",
            "department": "engineering",
            "version": 2,
        },
    },
    {
        "id": 6,
        "text": "Этические аспекты использования ИИ в государственном управлении...",
        "metadata": {
            "title": "ИИ и этика",
            "author": "А. Петров",
            "category": "наука",
            "tags": ["AI", "ethics", "governance"],
            "published_date": "2024-09-22T16:45:00Z",
            "rating": 4.5,
            "access_level": "public",
            "department": "research",
            "version": 1,
        },
    },
    {
        "id": 7,
        "text": "Обзор фреймворков для создания LLM-приложений (LangChain, LlamaIndex)...",
        "metadata": {
            "title": "Инструменты для LLM",
            "author": "К. Новиков",
            "category": "техника",
            "tags": ["AI", "LLM", "frameworks"],
            "published_date": "2025-02-28T13:10:00Z",
            "rating": 4.7,
            "access_level": "public",
            "department": "engineering",
            "version": 2,
        },
    },
]
